function [fitresult, gof] = createFit(Y, X1)
%CREATEFIT(Y,X1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Y
%      Y Output: X1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Dec-2017 23:07:14


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Y, X1 );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [X1(1),0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'X1 vs. Y', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel Y
% ylabel X1
% grid on


