function [fitresult, gof] = createFit(window_timestamp, window_sample)
%CREATEFIT(WINDOW_TIMESTAMP,WINDOW_SAMPLE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : window_timestamp
%      Y Output: window_sample
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Jul-2017 14:33:41


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( window_timestamp, window_sample );

% Set up fittype and options.
ft = 'pchip';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'window_sample vs. window_timestamp', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel window_timestamp
ylabel window_sample
grid on


